[package]
name = "rustic-asm"
version = "0.1.0"
authors = ["Matt Iselin <matthew@theiselions.net>"]
edition = "2018"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
