
[build]
target = "build-etc/i686-unknown-none.json"

[unstable]
build-std = ["core", "compiler_builtins", "panic_abort", "alloc"]
build-std-features = ["compiler-builtins-mem"]
extra-link-arg = true
