[package]
name = "rustic"
version = "0.1.0"
authors = ["Matt Iselin <matthew@theiselions.net>"]
edition = "2018"

[lib]
name = "rustic"
path = "rustic.rs"
crate-type = ["staticlib"]

[features]
default = ["arch_i386", "plat_pc"]

arch_i386 = []
plat_pc = []
plat_beagle = []
plat_rpi = []
